/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.Observable;
import java.util.Observer;
import modele.Partie;

/**
 *
 * @author Rasem
 */
public class PanelSynthese extends javax.swing.JPanel implements Observer{
    
    private Partie partie;

    /**
     * Creates new form PanelSynthese
     */
    public PanelSynthese() {
        partie.addObserver(this);
        initComponents();
    }
    
    public PanelSynthese(Partie partie) {
        this.partie = partie;
        //indique qu'on observe la partie 
        partie.addObserver(this);
        //creation des composants graphiques
        initComponents();
    }
    
    public void update(Observable objet, Object args) {
        if (partie == objet) {
            // mettre a jour les composants graphiques
            RepNbCoups.setText(partie.getNbCoups() + "");
            RepScoreA.setText(partie.getScoreA() + "");
            RepScoreB.setText(partie.getScoreB() + "");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NbCoups = new javax.swing.JLabel();
        ScoreA = new javax.swing.JLabel();
        ScoreB = new javax.swing.JLabel();
        RepNbCoups = new javax.swing.JLabel();
        RepScoreA = new javax.swing.JLabel();
        RepScoreB = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Synthèse"));

        NbCoups.setText("Nb de coups :");

        ScoreA.setText("Score de A :");

        ScoreB.setText("Score de B :");

        RepNbCoups.setText("0");

        RepScoreA.setText("0");

        RepScoreB.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NbCoups)
                    .addComponent(ScoreA)
                    .addComponent(ScoreB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RepScoreB)
                    .addComponent(RepScoreA)
                    .addComponent(RepNbCoups))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NbCoups)
                    .addComponent(RepNbCoups))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreA)
                    .addComponent(RepScoreA))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreB)
                    .addComponent(RepScoreB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NbCoups;
    private javax.swing.JLabel RepNbCoups;
    private javax.swing.JLabel RepScoreA;
    private javax.swing.JLabel RepScoreB;
    private javax.swing.JLabel ScoreA;
    private javax.swing.JLabel ScoreB;
    // End of variables declaration//GEN-END:variables
}
