/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.Observable;
import java.util.Observer;
import javax.swing.table.AbstractTableModel;
import modele.Partie;


/**
 *
 * @author Rasem
 */
public class PanelTableau extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form PanelTableau
     */
    Tableau modele;
    Partie partie;
    
    public PanelTableau() {
        modele=new Tableau();
        partie=new Partie();        
        initComponents();
        partie.addObserver(this);
        
    }
    public PanelTableau(Partie partie){
       modele=new Tableau();
        partie=new Partie();
        initComponents(); 
        partie.addObserver(this);
               
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(modele);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        modele.fireTableDataChanged();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private class Tableau extends AbstractTableModel {
        private String[] entetes = {"N°","Choix A","Choix B","Gain A","Gain B"};
        
        public Tableau() {
        }

        @Override
        public int getRowCount() {          
            return partie.getNbCoups();
        }
        @Override
        public String getColumnName(int columnIndex) {
        return entetes[columnIndex];
        }

        @Override
        public int getColumnCount() {
            return entetes.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            switch(columnIndex){
                case 0: return rowIndex +1;
                case 1: return partie.AaCoopere(rowIndex)?"C":"D";
                case 2: return partie.BaCoopere(rowIndex)?"C":"D"; 
                case 3: return partie.getGainA(rowIndex);
                case 4: return partie.getGainB(rowIndex);
                default: return "Erreur";
            }
        }
    }

}
